Create list and detail view for products
Karthikeyantestpress/Online_Shopping pull request #4
Opened 2022-11-17 09:11 UTC by Karthikeyantestpress

2022-11-24 09:16 UTC, waranlogesh requested changes

2022-11-24 09:16 UTC, waranlogesh commented on myshop/tests/shop/test_absolutepath.py
> +from django.test import TestCase
test_model_methods.py

2022-11-24 09:16 UTC, waranlogesh commented on myshop/tests/shop/test_absolutepath.py
> +class Test_model_method(ModelMixinTestCase, TestCase):
```suggestion
class TestModelMethod(ModelMixinTestCase, TestCase):

```

2022-11-24 09:16 UTC, waranlogesh commented on myshop/tests/shop/test_modelmixintestcase.py
> +from django.test import TestCase, Client
Underscore separate each words in the file name

2022-11-24 09:16 UTC, waranlogesh commented on myshop/tests/shop/test_views.py
> +        self.assertTemplateUsed(response, "shop/product/detail.html")
test_should_return_404_for_invalid_slug

2022-11-24 10:35 UTC, Karthikeyantestpress commented on myshop/tests/shop/test_views.py
> +        self.assertTemplateUsed(response, "shop/product/detail.html")
Updated Testcases  to return 404 for invalid slug

2022-11-24 10:35 UTC, Karthikeyantestpress commented on myshop/tests/shop/test_modelmixintestcase.py
> +from django.test import TestCase, Client
Updated

2022-11-29 10:20 UTC, waranlogesh approved these changes

2022-11-29 10:27 UTC, merged